### ISSUE TITLE
unable to play highlights and lowlights

### ISSUE THREAD

**Issue by ChengHeEric** [akiver/cs-demo-manager#1201]
### Describe the bug

Not sure is it related to the newest update by valve, the player highlights and lowlights are not working. 

### Steps to reproduce

1. start app
2. analyze demo
3. watch player highlight or lowlight
4. play the demo from the very beginning

### Expected behavior

expect the player highlights or lowlights 

### How often does this bug happen?

None

### Environment information

Version: 3.15.0
OS: win32 x64 10.0.26100
Electron: 37.3.1
Chrome: 138.0.7204.235
Last database migrations:
v8 - 2025-09-19T17:51:12.331Z

**Comment by michaelwang66** [comment]
same

**Comment by jumptosun** [comment]
Same question. It seems that Valve has changed how their subtick system works. It’s such a pain in the ass. every update messes up the demo system.

**Comment by sean8610** [comment]
same

**Comment by Julian332** [comment]
same

**Comment by akiver** [comment]
fixed with https://github.com/akiver/cs-demo-manager/pull/1198

**Comment by enterusernamecontinue** [comment]
> fixed with [#1198](https://github.com/akiver/cs-demo-manager/pull/1198)

Hi, Where can I download the latest version with the fixes? I see that the latest version available for download on the official website is 'v3.15.0 · 2025/9/7'.

**Comment by holgerschillack** [comment]
For me the error is not resolved.

All demos from the 17. September and following result in a game crash when trying to watch the highlights from the enemy's perspective.

Earlier demos are still working.

I got the latest update 3.15.1. on Windows.

Also tried to re-download the demos as well as re-analyze them.

**Comment by akiver** [comment]
> For me the error is not resolved.
> 
> All demos from the 17. September and following result in a game crash when trying to watch the highlights from the enemy's perspective.
> 
> Earlier demos are still working.
> 
> I got the latest update 3.15.1. on Windows.
> 
> Also tried to re-download the demos as well as re-analyze them.

Please create a new issue with a link to download the demo and steps to reproduce the issue.
Also make sure CS2 is up-to-date, the "CS2 plugin" is set to **Latest** in the playback settings and you are not using a custom CS2 build - see https://cs-demo-manager.com/docs/guides/playback#cs2-plugin-compatibility.
I just tried with a today demo and it works.
